# 정리 대상 폴더
target_folder: "C:/Users/drcho/OneDrive/문서/카카오톡 받은 파일"

#파일 분류 기준
file_types:
  이미지: [".jpg", ".jpeg", ".png", ".gif", ".bmp"]
  문서: [".pdf", ".docx", ".hwp", ".xlsx", ".pptx", ".txt"]
  압축: [".zip", ".rar", ".7z"]